# 禁用拓扑优化的配置 - 直接输出电力线检测结果
# 基于调试结果的最终配置

# 核心网格参数
grid_2d_size: 5.0          # 2D网格大小
voxel_size: 0.5            # 3D体素大小

# 预处理参数
sor_k: 20                  # SOR邻居数
sor_sigma: 2.0             # SOR标准差倍数

# 高度分析参数 (已验证有效)
min_height_gap: 10.0       # 最小高度间隙
tower_head_height: null    # 自动估算

# 特征计算参数 (已验证有效)
a1d_linear_thr: 0.6        # 线性阈值
a2d_planar_thr: 0.3        # 平面阈值
a3d_spherical_thr: 0.1     # 球形阈值

# 电力线提取参数
collinearity_angle_thr: 10.0    # Collinearity angle threshold in degrees
neighbor_mode: "8-connected"    # 2D grid neighborhood mode

# Tower segmentation parameters  
moving_window_size: 2           # 2x2 moving window for refinement
tower_grid_cluster_offset: 5.0  # H_h + 5 meters for clustering
planar_radius_offset: 5.0       # r + 5 for radius constraint

# Topological optimization parameters
connection_distance_thr: 10.0   # Max distance for PL-tower connections
parallel_angle_thr: 15.0        # Angle threshold for parallel consistency

# 输出参数
enable_visualization: true      # 开启可视化
save_intermediate: false        # 不保存中间结果 (避免LAS格式错误)
log_level: "INFO"               # 信息级别日志